In [3]:
import numpy as np
from numpy import linalg
import pandas as pd
import requests
from io import BytesIO
from zipfile import ZipFile

In [8]:
 """
  Задание 1
    """
def create_numpy_arr1(n):
    """
    Create numpy arr with range
    """
    return np.array([i for i in range(n)][::-1])

def create_numpy_arr2(n):
    return np.arange(n - 1, -1, -1)

print('Task 1. Numpy arrays:')
print(create_numpy_arr1(10))


Task 1. Numpy arrays:
[9 8 7 6 5 4 3 2 1 0]


In [10]:
 """
  Задание 2
    """
def create_diag_matrix(n):
    return np.diag(np.arange(n - 1, -1, -1))

print('Task 2. Diag matrix:')
dm = create_diag_matrix(10)
print(dm)
print(f'Sum of diag elems: {sum(dm.diagonal())}')


Task 2. Diag matrix:
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Sum of diag elems: 45


In [15]:
 """
  Задание 3
    """
left_side = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
])

right_side = np.array([4, 12, -3])
solution = linalg.solve(left_side, right_side)
x, y, z = solution


# check solution
if not np.allclose(np.dot(left_side, solution), right_side):
    raise RuntimeError('Incorrect solution!')

print(f'Task 5. Solution is: x = {x}, y = {y}, z = {z}')


Task 5. Solution is: x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555


In [18]:
"""
  Задание 5
    """

def get_movies_data_frame(zip_arch):
    """
    :return: pandas data frame with movies
    """
    return pd.read_csv(zip_arch.open(name='ml-latest-small/movies.csv'))

movies_zip = get_zip_files()
ratings = get_ratings_data_frame(movies_zip)
movies_info = get_movies_data_frame(movies_zip).set_index(keys='movieId', drop=False)


top_films = ratings.query('rating == {}'.format(5))

best_film_id = top_films['movieId'].value_counts().idxmax()

print(f'Task 3. Top movie: {movies_info.loc[best_film_id, "title"]}')


Task 3. Top movie: Shawshank Redemption, The (1994)


In [21]:
 """
  Задание 6
    """
power_data = pd.read_csv('power.csv')
sub_data = power_data.query('country in ("Latvia", "Lithuania", "Estonia") '
                            '& category in (4, 12, 21) & 2005 < year < 2010 & quantity >= 0')


print(f"Task 4. Total power consumption: {sub_data['quantity'].sum()}")


Task 4. Total power consumption: 164555.0
